# Generated by Django 5.0.2 on 2024-03-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Assign_To',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Reverted_By',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_emp_name', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Party_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('party_GST', models.CharField(blank=True, max_length=15)),
                ('party_address', models.CharField(blank=True, max_length=255)),
                ('party_city', models.CharField(blank=True, max_length=50)),
                ('party_state', models.CharField(blank=True, max_length=50)),
                ('party_mobile', models.IntegerField(blank=True)),
            ],
        ),
    ]
