# Generated by Django 5.0.2 on 2024-03-07 06:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Parent_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('order_assign_emp_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assign_emp', to='order_app.order_assign_to')),
                ('order_rev_emp_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rev_emp', to='order_app.order_reverted_by')),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='order_app.party_details')),
            ],
        ),
    ]
