# Generated by Django 5.0.2 on 2024-03-07 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_new_parent_order'),
        ('products', '0002_prod_cat_item_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Child_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_qty', models.IntegerField()),
                ('prod_price', models.IntegerField()),
                ('order_value', models.IntegerField()),
                ('gst_rate', models.IntegerField()),
                ('gst', models.FloatField()),
                ('total_value', models.FloatField()),
                ('Prod_cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_prod_cat', to='products.prod_category')),
                ('Prod_cat_list', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_cat_list', to='products.prod_cat_item_list')),
            ],
        ),
    ]
