# Generated by Django 5.0.2 on 2024-03-07 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_new_child_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_child_order',
            name='parent_order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='New_Parent', to='order_app.new_parent_order'),
            preserve_default=False,
        ),
    ]
