# Generated by Django 5.0.2 on 2024-02-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_books', to='demo.author'),
        ),
    ]
