# Generated by Django 5.0.2 on 2024-02-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_cat_name', models.CharField(max_length=255)),
                ('prod_cat_img', models.ImageField(upload_to='prod_cat_images/')),
                ('prod_cat_desc', models.CharField(max_length=255)),
            ],
        ),
    ]
